# Generated by Django 4.1 on 2022-08-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
